#
# Adds one layer to image-001.
#
# 3.file overwrites the file on the base image. It has the same size, but is
# otherwise completely different from the original file.
#

FROM image-001

COPY 3.file /
