---
version: "2.4"

services:
  sut:
    build: .
    privileged: true
    command:
      - |
        set -uaxe
        echo "-------- BUILDING --------"
        hack/make.sh dynbinary


#       echo "-------- UNIT TESTING --------"
#       hack/dind hack/test/unit
