FROM resin/amd64-golang:1.9

RUN apt-get update \
	&& apt-get install -y \
		btrfs-tools \
		libapparmor-dev \
		libdevmapper-dev \
		libnl-3-dev \
		libsystemd-dev \
		libsystemd-journal-dev \
		libudev-dev

COPY . /balena

WORKDIR /balena
