FROM resin/aarch64-golang:1.9

# Enable QEMU emulation
ENTRYPOINT [ "qemu-aarch64-static", "-execve" ]
SHELL      [ "qemu-aarch64-static", "-execve", "/bin/sh", "-c" ]

RUN apt-get update \
	&& apt-get install -y \
		btrfs-tools \
		libapparmor-dev \
		libdevmapper-dev \
		libnl-3-dev \
		libsystemd-dev

COPY . /balena

WORKDIR /balena
