#
# Adds one layer to image-001.
#
# 1.file overwrites the file on the base image. It has the same contents as the
# original file, plus some more data appended to it.
#

FROM image-001

COPY 1.file /
