#!/usr/bin/env bash
set -e

(
	[ -z "$KEEPDEST" ] && rm -rf "$DEST"
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$balena_BINARY_NAME"
	export GO_PACKAGE='github.com/docker/docker/cmd/balena-engine'
	export LDFLAGS="$LDFLAGS"
	export BUILDFLAGS=( "${BUILDFLAGS[@]/netgo /}" ) # disable netgo, since we don't need it for a dynamic binary
	source "${MAKEDIR}/.binary"
	source "${MAKEDIR}/.binary-symlinks"
)
