#!/usr/bin/env bash
set -e

(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$balena_BINARY_NAME"
	export GO_PACKAGE='github.com/docker/docker/cmd/balena-engine'
	export LDFLAGS="$LDFLAGS"
	export BUILDFLAGS=( "${BUILDFLAGS[@]/netgo /}" ) # disable netgo, since we don't need it for a dynamic binary
	source "${MAKEDIR}/.binary"

	for file in balena-engine-daemon balena-engine-containerd balena-engine-containerd-shim balena-engine-containerd-ctr balena-engine-runc balena-engine-proxy; do
		ln -sf $balena_BINARY_NAME "$DEST/$file"
	done
)
