#!/usr/bin/env bash
set -e
rm -rf "$DEST"

# This script exists as backwards compatibility for CI
(
	DEST="${DEST}-daemon"
	ABS_DEST="${ABS_DEST}-daemon"
	. hack/make/binary-daemon
	# balena-engine-proxy is a symlink to the balena-engine multicall binary
	# so we don't need to build a standalone binary-proxy
	. hack/make/.binary-symlinks
)
