#!/usr/bin/env bash
set -e

# if we have our linux/amd64 version compiled, let's symlink it in
if [ -x "${DEST}/../binary-daemon/dockerd-${VERSION}" ]; then
	arch=$(go env GOHOSTARCH)
	mkdir -p "$DEST/linux/${arch}"
	(
		cd "${DEST}/linux/${arch}"
		ln -sf ../../../binary-daemon/* ./
	)
	echo "Created symlinks:" "${DEST}/linux/${arch}/"*
fi

DOCKER_CROSSPLATFORMS=${DOCKER_CROSSPLATFORMS:-"linux/amd64"}

for platform in ${DOCKER_CROSSPLATFORMS}; do
	(
		export KEEPDEST=1
		export DEST="${DEST}/${platform}" # bundles/VERSION/cross/GOOS/GOARCH/docker-VERSION
		export GOOS=${platform%%/*}
		export GOARCH=${platform#*/}

		if [[ "${GOARCH}" = "arm/"* ]]; then
			GOARM=${GOARCH##*/v}
			GOARCH=${GOARCH%/v*}
			export GOARM
		fi

		# FIXME: gcc-multilib uninstalls gcc-arm compilers
		# worksaround to install during runtime and build linux/386 last
		# https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1300211
		if [[ "${GOARCH}" = "386" ]]; then
		    apt-get update && apt-get install -y --no-install-recommends gcc-multilib
		fi

		echo "Cross building: ${DEST}"
		mkdir -p "${DEST}"
		ABS_DEST="$(cd "${DEST}" && pwd -P)"
		source "${MAKEDIR}/binary-daemon"

		source "${MAKEDIR}/cross-platform-dependent"
	)
done
