#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && rm -rf "$DEST"

(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$balena_BINARY_NAME"
	export GO_PACKAGE='github.com/docker/docker/cmd/balenadctl'
	export IAMSTATIC='false'
	export LDFLAGS="$LDFLAGS"
	export LDFLAGS_STATIC_DOCKER=''
	export BUILDFLAGS=( "${BUILDFLAGS[@]/netgo /}" ) # disable netgo, since we don't need it for a dynamic binary
	export BUILDFLAGS=( "${BUILDFLAGS[@]/static_build /}" ) # we're not building a "static" binary
	source "${MAKEDIR}/.binary"
	copy_binaries "$DEST" 'hash'

	for file in balenad balena-containerd balena-containerd-shim balena-containerd-ctr balena-runc balena-proxy; do
		ln -sf $balena_BINARY_NAME "$DEST/$file"
	done
)
