#!/usr/bin/env bash
set -e

[ -z "$KEEPDEST" ] && rm -rf "$DEST"

(
	export LDFLAGS_STATIC=''
	export BUILDFLAGS=("${BUILDFLAGS[@]/netgo /}")        # disable netgo, since we don't need it for a dynamic binary
	export BUILDFLAGS=("${BUILDFLAGS[@]/osusergo /}")     # ditto for osusergo
	export BUILDFLAGS=("${BUILDFLAGS[@]/static_build /}") # we're not building a "static" binary here

	GO_PACKAGE='github.com/docker/docker/cmd/balena-engine'
	BINARY_NAME='balena-engine'
	source "${MAKEDIR}/.binary"
)

# Create symlinks for busybox-style dispatch
# The balena-engine binary dispatches based on argv[0]
echo "Creating symlinks for busybox-style binary..."
for name in balena-engine-daemon balena-engine-containerd balena-engine-containerd-shim-runc-v2 balena-engine-containerd-ctr balena-engine-runc balena-engine-proxy balena-runc balena-containerd balenad balena; do
	ln -sf "balena-engine" "$DEST/$name"
done
echo "Created symlinks in $DEST"
