#!/usr/bin/env bash
set -e

(
	[ -z "$KEEPDEST" ] && rm -rf "$DEST"
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$balena_BINARY_NAME"
	export GO_PACKAGE='github.com/docker/docker/cmd/balena-engine'
	export IAMSTATIC='false'
	export LDFLAGS_STATIC_DOCKER=''
	export BUILDFLAGS=( "${BUILDFLAGS[@]/netgo /}" ) # disable netgo, since we don't need it for a dynamic binary
	export BUILDFLAGS=( "${BUILDFLAGS[@]/osusergo /}" ) # ditto for osusergo
	export BUILDFLAGS=( "${BUILDFLAGS[@]/static_build /}" ) # we're not building a "static" binary here
	source "${MAKEDIR}/.binary"
	source "${MAKEDIR}/.binary-symlinks"
)
